2022-12-06 11:55:16,266 INFO    Thread-8  :2521097 [wandb_setup.py:_flush():68] Configure stats pid to 2521097
2022-12-06 11:55:16,266 INFO    Thread-8  :2521097 [wandb_setup.py:_flush():68] Loading settings from /home/sin/.config/wandb/settings
2022-12-06 11:55:16,266 INFO    Thread-8  :2521097 [wandb_setup.py:_flush():68] Loading settings from /home/sin/PycharmProjects/tutorial/wandb/settings
2022-12-06 11:55:16,266 INFO    Thread-8  :2521097 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True', 'entity': 'sb2539', 'project': 'dbscan_demo_outlier', 'root_dir': '/home/sin/PycharmProjects/tutorial', 'sweep_id': 'qbjjlenu', 'run_id': '0j4px51g', 'sweep_param_path': '/home/sin/PycharmProjects/tutorial/wandb/sweep-qbjjlenu/config-0j4px51g.yaml'}
2022-12-06 11:55:16,267 INFO    Thread-8  :2521097 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'dbscan.py', 'program': '/home/sin/PycharmProjects/tutorial/dbscan.py'}
2022-12-06 11:55:16,267 INFO    Thread-8  :2521097 [wandb_init.py:_log_setup():476] Logging user logs to /home/sin/PycharmProjects/tutorial/wandb/run-20221206_115516-0j4px51g/logs/debug.log
2022-12-06 11:55:16,267 INFO    Thread-8  :2521097 [wandb_init.py:_log_setup():477] Logging internal logs to /home/sin/PycharmProjects/tutorial/wandb/run-20221206_115516-0j4px51g/logs/debug-internal.log
2022-12-06 11:55:16,267 INFO    Thread-8  :2521097 [wandb_init.py:init():516] calling init triggers
2022-12-06 11:55:16,267 INFO    Thread-8  :2521097 [wandb_init.py:init():520] wandb.init called with sweep_config: {'eps': [0.1, 0.01, 0.02, 0.03, 0.04, 0.05], 'min_sample': [6, 7, 8, 9, 10]}
config: {}
2022-12-06 11:55:16,268 INFO    Thread-8  :2521097 [wandb_init.py:init():564] wandb.init() called when a run is still active
2022-12-06 11:55:16,284 ERROR   Thread-8  :2521097 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 566, in init
    tel.feature.init_return_run = True
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/site-packages/wandb/sdk/lib/telemetry.py", line 40, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 608, in _telemetry_callback
    self._telemetry_flush()
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 619, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 97, in _publish_telemetry
    self._publish(rec)
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
