2022-12-06 15:00:35,346 INFO    Thread-9  :2540322 [wandb_setup.py:_flush():68] Configure stats pid to 2540322
2022-12-06 15:00:35,346 INFO    Thread-9  :2540322 [wandb_setup.py:_flush():68] Loading settings from /home/sin/.config/wandb/settings
2022-12-06 15:00:35,346 INFO    Thread-9  :2540322 [wandb_setup.py:_flush():68] Loading settings from /home/sin/PycharmProjects/tutorial/wandb/settings
2022-12-06 15:00:35,346 INFO    Thread-9  :2540322 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True', 'entity': 'sb2539', 'project': 'dbscan_demo_outlier', 'root_dir': '/home/sin/PycharmProjects/tutorial', 'run_id': 'z3nax9is', 'sweep_param_path': '/home/sin/PycharmProjects/tutorial/wandb/sweep-7lucpm09/config-z3nax9is.yaml', 'sweep_id': '7lucpm09'}
2022-12-06 15:00:35,346 INFO    Thread-9  :2540322 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'dbscan.py', 'program': '/home/sin/PycharmProjects/tutorial/dbscan.py'}
2022-12-06 15:00:35,346 INFO    Thread-9  :2540322 [wandb_init.py:_log_setup():476] Logging user logs to /home/sin/PycharmProjects/tutorial/wandb/run-20221206_150035-z3nax9is/logs/debug.log
2022-12-06 15:00:35,346 INFO    Thread-9  :2540322 [wandb_init.py:_log_setup():477] Logging internal logs to /home/sin/PycharmProjects/tutorial/wandb/run-20221206_150035-z3nax9is/logs/debug-internal.log
2022-12-06 15:00:35,346 INFO    Thread-9  :2540322 [wandb_init.py:init():516] calling init triggers
2022-12-06 15:00:35,347 INFO    Thread-9  :2540322 [wandb_init.py:init():520] wandb.init called with sweep_config: {'eps': 0.05, 'min_sample': 10}
config: {}
2022-12-06 15:00:35,347 INFO    Thread-9  :2540322 [wandb_init.py:init():569] starting backend
2022-12-06 15:00:35,347 INFO    Thread-9  :2540322 [wandb_init.py:init():573] setting up manager
2022-12-06 15:00:35,353 INFO    Thread-9  :2540322 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-12-06 15:00:35,357 INFO    Thread-9  :2540322 [wandb_init.py:init():580] backend started and connected
2022-12-06 15:00:35,363 INFO    Thread-9  :2540322 [wandb_run.py:_config_callback():1160] config_cb None None {'eps': 0.05, 'min_sample': 10}
2022-12-06 15:00:35,366 INFO    Thread-9  :2540322 [wandb_init.py:init():658] updated telemetry
2022-12-06 15:00:35,366 INFO    Thread-9  :2540322 [wandb_init.py:init():694] communicating run to backend with 60 second timeout
2022-12-06 15:00:35,967 INFO    Thread-9  :2540322 [wandb_run.py:_on_init():2000] communicating current version
2022-12-06 15:00:36,104 INFO    Thread-9  :2540322 [wandb_run.py:_on_init():2004] got version response 
2022-12-06 15:00:36,104 INFO    Thread-9  :2540322 [wandb_init.py:init():728] starting run threads in backend
2022-12-06 15:00:38,250 ERROR   Thread-9  :2540322 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 739, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 235, in communicate_run_start
    result = self._communicate_run_start(run_start)
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 484, in _communicate_run_start
    result = self._communicate(rec)
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 255, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/site-packages/wandb/sdk/interface/router.py", line 36, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/home/sin/anaconda3/envs/semi/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
Exception
